name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight, adjust as needed

jobs:
  terraform-cleanup:
    name: 'Post Apply Cleanup'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.4.0'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ secrets.AWS_ROLE }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Plan Destroy'
      run: terraform plan -destroy -out=tfplan-destroy

    - name: 'Terraform Apply Destroy'
      run: terraform apply -auto-approve tfplan-destroy
